-- megafunction wizard: %ALTIOBUF%
-- GENERATION: STANDARD
-- VERSION: WM1.0
-- MODULE: altiobuf_bidir 

-- ============================================================
-- File Name: iobuf.vhd
-- Megafunction Name(s):
-- 			altiobuf_bidir
--
-- Simulation Library Files(s):
-- 			cyclone10lp
-- ============================================================
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
--
-- 20.1.0 Build 711 06/05/2020 SJ Lite Edition
-- ************************************************************


--Copyright (C) 2020  Intel Corporation. All rights reserved.
--Your use of Intel Corporation's design tools, logic functions 
--and other software and tools, and any partner logic 
--functions, and any output files from any of the foregoing 
--(including device programming or simulation files), and any 
--associated documentation or information are expressly subject 
--to the terms and conditions of the Intel Program License 
--Subscription Agreement, the Intel Quartus Prime License Agreement,
--the Intel FPGA IP License Agreement, or other applicable license
--agreement, including, without limitation, that your use is for
--the sole purpose of programming logic devices manufactured by
--Intel and sold by Intel or its authorized distributors.  Please
--refer to the applicable agreement for further details, at
--https://fpgasoftware.intel.com/eula.


--altiobuf_bidir CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone 10 LP" ENABLE_BUS_HOLD="FALSE" NUMBER_OF_CHANNELS=8 OPEN_DRAIN_OUTPUT="FALSE" USE_DIFFERENTIAL_MODE="FALSE" USE_DYNAMIC_TERMINATION_CONTROL="FALSE" USE_TERMINATION_CONTROL="FALSE" datain dataio dataout oe
--VERSION_BEGIN 20.1 cbx_altiobuf_bidir 2020:06:05:12:04:24:SJ cbx_mgl 2020:06:05:13:25:21:SJ cbx_stratixiii 2020:06:05:12:04:24:SJ cbx_stratixv 2020:06:05:12:04:24:SJ  VERSION_END

 Library UNISIM;
 use UNISIM.vcomponents.all;

--synthesis_resources = cyclone10lp_io_ibuf 8 cyclone10lp_io_obuf 8 
 LIBRARY ieee;
 USE ieee.std_logic_1164.all;

 ENTITY  iobuf_iobuf_bidir_30p IS 
	 PORT 
	 ( 
		 datain	:	IN  STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
		 dataio	:	INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
		 dataout	:	OUT  STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
		 oe	:	IN  STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '1')
	 ); 
 END iobuf_iobuf_bidir_30p;

 ARCHITECTURE RTL OF iobuf_iobuf_bidir_30p IS

	 SIGNAL  wire_ibufa_i	:	STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
	 SIGNAL  wire_ibufa_o	:	STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
	 SIGNAL  wire_obufa_i	:	STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
	 SIGNAL  wire_obufa_o	:	STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
	 SIGNAL  wire_obufa_oe	:	STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '1');
	 
 BEGIN
    loop0 : FOR i IN 0 TO 7 GENERATE 
        IOBUF_inst : IOBUF
       generic map (
          DRIVE => 12,
          IOSTANDARD => "DEFAULT",
          SLEW => "SLOW")
       port map (
          O => dataout(i),     -- Buffer output
          IO => dataio(i),   -- Buffer inout port (connect directly to top-level port)
          I => datain(i),     -- Buffer input
          T => not oe(i)      -- 3-state enable input, high=input, low=output 
       );
       END GENERATE;
 END RTL; --iobuf_iobuf_bidir_30p
--VALID FILE


--LIBRARY ieee;
--USE ieee.std_logic_1164.all;

--ENTITY iobuf IS
--	PORT
--	(
--		datain		: IN STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
--		oe		: IN STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
--		dataio		: INOUT STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
--		dataout		: OUT STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0')
--	);
--END iobuf;


--ARCHITECTURE RTL OF iobuf IS

--	SIGNAL sub_wire0	: STD_LOGIC_VECTOR (7 DOWNTO 0);



--	COMPONENT iobuf_iobuf_bidir_30p
--	PORT (
--			datain	: IN STD_LOGIC_VECTOR (7 DOWNTO 0);
--			oe	: IN STD_LOGIC_VECTOR (7 DOWNTO 0);
--			dataout	: OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
--			dataio	: INOUT STD_LOGIC_VECTOR (7 DOWNTO 0)
--	);
--	END COMPONENT;

--BEGIN
--	dataout    <= sub_wire0(7 DOWNTO 0);

--	iobuf_iobuf_bidir_30p_component : iobuf_iobuf_bidir_30p
--	PORT MAP (
--		datain => datain,
--		oe => oe,
--		dataout => sub_wire0,
--		dataio => dataio
--	);



--END RTL;

-- ============================================================
-- CNX file retrieval info
-- ============================================================
-- Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone 10 LP"
-- Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
-- Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
-- Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone 10 LP"
-- Retrieval info: CONSTANT: enable_bus_hold STRING "FALSE"
-- Retrieval info: CONSTANT: number_of_channels NUMERIC "8"
-- Retrieval info: CONSTANT: open_drain_output STRING "FALSE"
-- Retrieval info: CONSTANT: use_differential_mode STRING "FALSE"
-- Retrieval info: CONSTANT: use_dynamic_termination_control STRING "FALSE"
-- Retrieval info: CONSTANT: use_termination_control STRING "FALSE"
-- Retrieval info: USED_PORT: datain 0 0 8 0 INPUT NODEFVAL "datain[7..0]"
-- Retrieval info: USED_PORT: dataio 0 0 8 0 BIDIR NODEFVAL "dataio[7..0]"
-- Retrieval info: USED_PORT: dataout 0 0 8 0 OUTPUT NODEFVAL "dataout[7..0]"
-- Retrieval info: USED_PORT: oe 0 0 8 0 INPUT NODEFVAL "oe[7..0]"
-- Retrieval info: CONNECT: @datain 0 0 8 0 datain 0 0 8 0
-- Retrieval info: CONNECT: @oe 0 0 8 0 oe 0 0 8 0
-- Retrieval info: CONNECT: dataio 0 0 8 0 @dataio 0 0 8 0
-- Retrieval info: CONNECT: dataout 0 0 8 0 @dataout 0 0 8 0
-- Retrieval info: GEN_FILE: TYPE_NORMAL iobuf.vhd TRUE
-- Retrieval info: GEN_FILE: TYPE_NORMAL iobuf.inc FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL iobuf.cmp TRUE
-- Retrieval info: GEN_FILE: TYPE_NORMAL iobuf.bsf FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL iobuf_inst.vhd FALSE
-- Retrieval info: LIB_FILE: cyclone10lp
