# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VivadoResources/zyboZ7Master.xdc

# Block Designs: bd/mOISC/mOISC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC || ORIG_REF_NAME==mOISC} -quiet] -quiet

# IP: bd/mOISC/ip/mOISC_clashAlu_0_0/mOISC_clashAlu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC_clashAlu_0_0 || ORIG_REF_NAME==mOISC_clashAlu_0_0} -quiet] -quiet

# IP: bd/mOISC/ip/mOISC_clashIoCtr_0_0/mOISC_clashIoCtr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC_clashIoCtr_0_0 || ORIG_REF_NAME==mOISC_clashIoCtr_0_0} -quiet] -quiet

# IP: bd/mOISC/ip/mOISC_clashMem_0_0/mOISC_clashMem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC_clashMem_0_0 || ORIG_REF_NAME==mOISC_clashMem_0_0} -quiet] -quiet

# IP: bd/mOISC/ip/mOISC_clashFsm_0_0/mOISC_clashFsm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC_clashFsm_0_0 || ORIG_REF_NAME==mOISC_clashFsm_0_0} -quiet] -quiet

# IP: bd/mOISC/ip/mOISC_clashIoBuffer_0_0/mOISC_clashIoBuffer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC_clashIoBuffer_0_0 || ORIG_REF_NAME==mOISC_clashIoBuffer_0_0} -quiet] -quiet

# IP: bd/mOISC/ip/mOISC_clashClockGen_0_0/mOISC_clashClockGen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC_clashClockGen_0_0 || ORIG_REF_NAME==mOISC_clashClockGen_0_0} -quiet] -quiet

# IP: bd/mOISC/ip/mOISC_clk_wiz_0_0/mOISC_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC_clk_wiz_0_0 || ORIG_REF_NAME==mOISC_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mOISC/ip/mOISC_util_vector_logic_0_0/mOISC_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mOISC_util_vector_logic_0_0 || ORIG_REF_NAME==mOISC_util_vector_logic_0_0} -quiet] -quiet

# XDC: d:/git/clash-moisc/Vivado/MoiscBlocks/MoiscBlocks.gen/sources_1/bd/mOISC/mOISC_ooc.xdc
