# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MonadmOISC/MonadmOISC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MonadmOISC || ORIG_REF_NAME==MonadmOISC} -quiet] -quiet

# IP: bd/MonadmOISC/ip/MonadmOISC_clashFsmMonad_0_0/MonadmOISC_clashFsmMonad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MonadmOISC_clashFsmMonad_0_0 || ORIG_REF_NAME==MonadmOISC_clashFsmMonad_0_0} -quiet] -quiet

# IP: bd/MonadmOISC/ip/MonadmOISC_clashMem_0_0/MonadmOISC_clashMem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MonadmOISC_clashMem_0_0 || ORIG_REF_NAME==MonadmOISC_clashMem_0_0} -quiet] -quiet

# IP: bd/MonadmOISC/ip/MonadmOISC_clashAlu_0_0/MonadmOISC_clashAlu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MonadmOISC_clashAlu_0_0 || ORIG_REF_NAME==MonadmOISC_clashAlu_0_0} -quiet] -quiet

# IP: bd/MonadmOISC/ip/MonadmOISC_clashClockGen_0_0/MonadmOISC_clashClockGen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MonadmOISC_clashClockGen_0_0 || ORIG_REF_NAME==MonadmOISC_clashClockGen_0_0} -quiet] -quiet

# IP: bd/MonadmOISC/ip/MonadmOISC_clashIoBuffer_0_0/MonadmOISC_clashIoBuffer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MonadmOISC_clashIoBuffer_0_0 || ORIG_REF_NAME==MonadmOISC_clashIoBuffer_0_0} -quiet] -quiet

# IP: bd/MonadmOISC/ip/MonadmOISC_clashIoCtr_0_0/MonadmOISC_clashIoCtr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MonadmOISC_clashIoCtr_0_0 || ORIG_REF_NAME==MonadmOISC_clashIoCtr_0_0} -quiet] -quiet

# XDC: d:/git/clash-moisc/Vivado/MoiscBlocksMonad/MoiscBlocksMonad.gen/sources_1/bd/MonadmOISC/MonadmOISC_ooc.xdc
